version: '3.8'
services:
  couchdb:
    image: couchdb:3.2.0
    container_name: cdb
    ports:
      - '5984:5984'
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 30s
      timeout: 10s
      retries: 5
  server:
    build: ./server
    container_name: server
    ports:
      - '8080:8080'
    depends_on:
      couchdb:
        condition: service_healthy
  app:
    build: ./app
    container_name: rapp_c
    ports:
      - '3000:3000'